import fs from "node:fs/promises";
import { FileBlob, SpreadsheetFile } from "@oai/artifact-tool";

const root="/workspace/scratch/82fa5d97afa7/retail_credit_pd_model";
const source=`${root}/outputs/v6/model_validation_pack_v6.xlsx`, outDir=`${root}/outputs/v7`, out=`${outDir}/model_validation_pack_v7.xlsx`, previews=`${outDir}/previews`;
const p=JSON.parse(await fs.readFile(`${root}/reports/validation_payload.json`,"utf8")); await fs.mkdir(previews,{recursive:true});
const wb=await SpreadsheetFile.importXlsx(await FileBlob.load(source));
const sourcePreview=await wb.render({sheetName:"V6 Summary",autoCrop:"all",scale:1,format:"png"}); await fs.writeFile(`${previews}/source_v6_summary.png`,new Uint8Array(await sourcePreview.arrayBuffer()));
const navy="#123455",gold="#F2B705",blue="#DDEBF7",pale="#EDF4F8",green="#E2F0D9",amber="#FFF2CC",font="Arial",pct="0.0%",money='"VND "#,##0;[Red]("VND "#,##0);-';
function sheet(name,title,subtitle){const s=wb.worksheets.add(name);s.showGridLines=false;s.getRange("A2:J2").merge();s.getRange("A2").values=[[title]];s.getRange("A2:J2").format={font:{name:font,size:16,bold:true,color:navy},rowHeight:27};s.getRange("A3:J3").merge();s.getRange("A3").values=[[subtitle]];s.getRange("A3:J3").format={font:{name:font,size:10,italic:true,color:"#666666"},rowHeight:19};s.getRange("A4:J4").format.borders={bottom:{style:"medium",color:gold}};return s}
function header(r){r.format={fill:navy,font:{name:font,size:10,bold:true,color:"#FFFFFF"},horizontalAlignment:"center",verticalAlignment:"center",wrapText:true,rowHeight:28}}
function body(r){r.format={font:{name:font,size:10,color:"#1F1F1F"},verticalAlignment:"center",wrapText:true,borders:{insideHorizontal:{style:"thin",color:"#D9E2F3"}}}}

const s=sheet("V7 TNEX Summary","V7 TNEX Digital Lending Decisioning","TNEX-aligned synthetic portfolio • configurable product policy • not an official TNEX model or affiliated implementation");
s.getRange("A6:B14").values=[["Metric","Result"],["Build",p.v7_summary.build],["Applications",p.v7_summary.applications],["Products",p.v7_summary.products],["Approval rate",p.v7_summary.approval_rate],["Fraud decline rate",p.v7_summary.fraud_decline_rate],["P95 end-to-end",p.v7_summary.p95_end_to_end_ms],["Start-to-disbursement",p.v7_summary.disbursement_conversion],["Status",p.v7_summary.overall_status]];header(s.getRange("A6:B6"));body(s.getRange("A7:B14"));s.getRange("B10:B11").format.numberFormat=pct;s.getRange("B12").format.numberFormat='0 "ms"';s.getRange("B13").format.numberFormat=pct;
s.getRange("D6:H6").merge();s.getRange("D6").values=[["Executive decision"]];header(s.getRange("D6:H6"));s.getRange("D7:H9").merge();s.getRange("D7").values=[["PASS — SIMULATION. The design supports Cash Loan, BNPL and Business Loan through separate policies, independent fraud and credit scores, and a measured digital funnel. P95 orchestration remains below the five-second target."]];s.getRange("D7:H9").format={fill:pale,font:{name:font,size:11,color:navy},wrapText:true,verticalAlignment:"center"};
s.getRange("D11:H11").merge();s.getRange("D11").values=[["Production boundary"]];header(s.getRange("D11:H11"));s.getRange("D12:H14").merge();s.getRange("D12").values=[["Replace synthetic data and public product assumptions; complete consent/privacy review, independent validation, live calibration, legal/compliance approval, ledger integration, shadow scoring and canary release before production use."]];s.getRange("D12:H14").format={fill:amber,font:{name:font,size:10,bold:true,color:"#7F6000"},wrapText:true,verticalAlignment:"center"};s.getRange("A:A").format.columnWidth=25;s.getRange("B:B").format.columnWidth=20;s.getRange("D:H").format.columnWidth=15;

const d=sheet("Product Decisioning","Product Policy and Decision Performance","Blue selector drives the formula-based executive view; limits and cut-offs are versioned assumptions");
d.getRange("A6:B6").values=[["Selected product",p.v7_product_config[0].product]];header(d.getRange("A6"));d.getRange("B6").format={fill:blue,font:{name:font,size:10,bold:true,color:"#0000FF"}};
const cfg=p.v7_product_config, perf=p.v7_product_performance;d.getRange("A9:H9").values=[["Product","Label","Max limit","Approve PD","Review PD","Fraud max","Policy version","Effective date"]];d.getRangeByIndexes(9,0,cfg.length,8).values=cfg.map(x=>[x.product,x.label,x.max_limit_vnd,x.approve_pd_max,x.review_pd_max,x.fraud_max,x.policy_version,x.effective_date]);header(d.getRange("A9:H9"));body(d.getRange("A10:H12"));d.getRange("C10:C12").format.numberFormat=money;d.getRange("D10:F12").format.numberFormat=pct;
d.getRange("A15:H15").values=[["Product","Applications","Approval","Review","Fraud decline","Mean PD","Approved limit","P95 latency"]];d.getRangeByIndexes(15,0,perf.length,8).values=perf.map(x=>[x.product,x.applications,x.approval_rate,x.review_rate,x.fraud_decline_rate,x.mean_decision_pd,x.approved_limit_vnd,x.p95_latency_ms]);header(d.getRange("A15:H15"));body(d.getRange("A16:H18"));d.getRange("C16:F18").format.numberFormat=pct;d.getRange("G16:G18").format.numberFormat=money;d.getRange("H16:H18").format.numberFormat='0 "ms"';
d.getRange("D6:H6").values=[["Applications","Approval","Fraud decline","Approved limit","P95 latency"]];header(d.getRange("D6:H6"));d.getRange("D7").formulas=[["=SUMIF(A16:A18,B6,B16:B18)"]];d.getRange("E7").formulas=[["=SUMIF(A16:A18,B6,C16:C18)"]];d.getRange("F7").formulas=[["=SUMIF(A16:A18,B6,E16:E18)"]];d.getRange("G7").formulas=[["=SUMIF(A16:A18,B6,G16:G18)"]];d.getRange("H7").formulas=[["=SUMIF(A16:A18,B6,H16:H18)"]];d.getRange("E7:F7").format.numberFormat=pct;d.getRange("G7").format.numberFormat=money;d.getRange("H7").format.numberFormat='0 "ms"';d.getRange("A:A").format.columnWidth=20;d.getRange("B:B").format.columnWidth=24;d.getRange("C:H").format.columnWidth=17;d.freezePanes.freezeRows(9);

const f=sheet("Digital Funnel","Digital Acquisition and Decision Funnel","Counts reconcile from application start through disbursement or activation");const fu=p.v7_funnel;f.getRange("A6:D6").values=[["Stage","Customers","Conversion from prior","Conversion from start"]];f.getRangeByIndexes(6,0,fu.length,4).values=fu.map(x=>[x.stage,x.customers,x.conversion_from_prior,x.conversion_from_start]);header(f.getRange("A6:D6"));body(f.getRange(`A7:D${6+fu.length}`));f.getRange(`C7:D${6+fu.length}`).format.numberFormat=pct;f.getRange("A:A").format.columnWidth=32;f.getRange("B:D").format.columnWidth=22;
const lat=p.v7_latency;f.getRange("F6:I6").values=[["Component","P50 ms","P95 ms","SLA ms"]];f.getRangeByIndexes(6,5,lat.length,4).values=lat.map(x=>[x.component,x.p50_ms,x.p95_ms,x.sla_ms]);header(f.getRange("F6:I6"));body(f.getRange(`F7:I${6+lat.length}`));f.getRange("F:F").format.columnWidth=25;f.getRange("G:I").format.columnWidth=16;

const l=sheet("Lifecycle Controls","Repeat-customer and Collections Controls","Limit management is explainable; unresolved payments suppress automated collection reminders");const lc=p.v7_lifecycle;l.getRange("A6:D6").values=[["Lifecycle action","Customers","Mean PD","Mean on-time ratio"]];l.getRangeByIndexes(6,0,lc.length,4).values=lc.map(x=>[x.lifecycle_action,x.customers,x.mean_pd,x.mean_on_time_ratio]);header(l.getRange("A6:D6"));body(l.getRangeByIndexes(6,0,lc.length,4));l.getRange(`C7:D${6+lc.length}`).format.numberFormat=pct;
const co=p.v7_collections;l.getRange("A14:G14").values=[["Control","Population","Exceptions","Exception rate","SLA","Action","Status"]];l.getRangeByIndexes(14,0,co.length,7).values=co.map(x=>[x.control,x.population,x.exceptions,x.rate,x.sla,x.action,x.status]);header(l.getRange("A14:G14"));body(l.getRangeByIndexes(14,0,co.length,7));l.getRange("D15:D18").format.numberFormat=pct;l.getRange("A:A").format.columnWidth=32;l.getRange("B:D").format.columnWidth=18;l.getRange("E:E").format.columnWidth=16;l.getRange("F:F").format.columnWidth=48;l.getRange("G:G").format.columnWidth=14;
const fg=p.v7_feature_governance;l.getRange("F6:K6").values=[["Feature group","Feature","Freshness","Consent","Fallback","Owner"]];l.getRangeByIndexes(6,5,fg.length,6).values=fg.map(x=>[x.feature_group,x.feature,x.freshness_sla,x.consent_required,x.fallback,x.owner]);header(l.getRange("F6:K6"));body(l.getRangeByIndexes(6,5,fg.length,6));l.getRange("F:K").format.columnWidth=22;l.getRange("J:J").format.columnWidth=31;

wb.recalculate();const checks=[];for(const [sn,range] of [["V7 TNEX Summary","A2:H14"],["Product Decisioning","A2:H18"],["Digital Funnel","A2:I12"],["Lifecycle Controls","A2:K18"]])checks.push((await wb.inspect({kind:"table",range:`${sn}!${range}`,include:"values,formulas",tableMaxRows:24,tableMaxCols:12})).ndjson);
d.getRange("B6").values=[["BNPL"]];wb.recalculate();checks.push((await wb.inspect({kind:"table",range:"Product Decisioning!B6:H7",include:"values,formulas",tableMaxRows:3,tableMaxCols:8})).ndjson);d.getRange("B6").values=[[cfg[0].product]];wb.recalculate();
const errors=await wb.inspect({kind:"match",searchTerm:"#REF!|#DIV/0!|#VALUE!|#NAME\\?|#N/A|#NUM!|#NULL!|#SPILL!|#CALC!",options:{useRegex:true,maxResults:300},summary:"final formula error scan"});checks.push(errors.ndjson);await fs.writeFile(`${out}.inspect.ndjson`,checks.join("\n"));
for(const name of ["V7 TNEX Summary","Product Decisioning","Digital Funnel","Lifecycle Controls"]){const b=await wb.render({sheetName:name,autoCrop:"all",scale:1,format:"png"});await fs.writeFile(`${previews}/${name.toLowerCase().replaceAll(" ","_")}.png`,new Uint8Array(await b.arrayBuffer()))}
const blob=await SpreadsheetFile.exportXlsx(wb);await blob.save(out);console.log(JSON.stringify({outputPath:out,sheetsAdded:4,errorScan:errors.ndjson}));
