import fs from "node:fs/promises";
import { FileBlob, SpreadsheetFile } from "@oai/artifact-tool";

const root = "/workspace/scratch/82fa5d97afa7/retail_credit_pd_model";
const source = `${root}/outputs/v5/model_validation_pack_v5.xlsx`;
const outputDir = `${root}/outputs/v6`;
const outputPath = `${outputDir}/model_validation_pack_v6.xlsx`;
const previewDir = `${outputDir}/previews`;
const p = JSON.parse(await fs.readFile(`${root}/reports/validation_payload.json`, "utf8"));
await fs.mkdir(previewDir, { recursive: true });
const wb = await SpreadsheetFile.importXlsx(await FileBlob.load(source));
const sourcePreview = await wb.render({ sheetName: "V5 Summary", autoCrop: "all", scale: 1, format: "png" });
await fs.writeFile(`${previewDir}/source_v5_summary.png`, new Uint8Array(await sourcePreview.arrayBuffer()));

const navy="#123455", gold="#F2B705", pale="#D9EAF7", green="#E2F0D9", amber="#FFF2CC", red="#FCE4D6", gray="#E7E6E6", font="Arial";
const money='"VND "#,##0;[Red]("VND "#,##0);-';
const pct="0.0%";
function addSheet(name,title,subtitle){const s=wb.worksheets.add(name);s.showGridLines=false;s.getRange("A2").values=[[title]];s.getRange("A2:J2").format={font:{name:font,size:15,bold:true,color:navy},rowHeight:25};s.getRange("A3").values=[[subtitle]];s.getRange("A3:J3").format={font:{name:font,size:10,italic:true,color:"#666666"},rowHeight:20};s.getRange("A4:J4").format.borders={bottom:{style:"thin",color:gold}};return s}
function header(r){r.format={fill:navy,font:{name:font,size:10,bold:true,color:"#FFFFFF"},horizontalAlignment:"center",verticalAlignment:"center",wrapText:true,rowHeight:30}}
function body(r){r.format.font={name:font,size:10,color:"#1F1F1F"};r.format.verticalAlignment="center";r.format.borders={insideHorizontal:{style:"thin",color:"#D9E2F3"}}}

const summary=addSheet("V6 Summary","V6 Bank-Grade Deployment & IFRS 9 Summary","Outcome-maturity controls, component validation, probability-weighted ECL and safe rollback evidence");
summary.getRange("A6:B15").values=[
 ["Metric","Result"],["Build",p.v6_summary.build],["Overall status",p.v6_summary.overall_status],["Monitoring months",p.v6_summary.monitoring_months],["Mature months",p.v6_summary.mature_months],["LGD validation",p.v6_summary.lgd_status],["EAD validation",p.v6_summary.ead_status],["Weighted ECL",p.v6_summary.weighted_ecl],["Stage 2–3 share",p.v6_summary.stage_2_3_share],["Rollout status",p.v6_summary.rollout_status]
];header(summary.getRange("A6:B6"));body(summary.getRange("A7:B15"));summary.getRange("B13").format.numberFormat=money;summary.getRange("B14").format.numberFormat=pct;
summary.getRange("D6").values=[["Validation conclusion"]];header(summary.getRange("D6"));summary.getRange("D7").values=[["LGD and EAD proxy models pass their synthetic validation thresholds. Recent cohorts do not report outcome-dependent metrics until labels mature. The 25% canary fails its operational gates, full rollout is blocked and the stable release is restored through five completed rollback controls."]];summary.getRange("D7").format={fill:pale,font:{name:font,size:11,color:navy},wrapText:true,verticalAlignment:"top",rowHeight:95};
summary.getRange("D10").values=[["Decision"]];header(summary.getRange("D10"));summary.getRange("D11").values=[["CONDITIONAL PASS. Use the workflow as portfolio evidence only. Replace synthetic recovery, utilization and macroeconomic assumptions before bank deployment or financial reporting."]];summary.getRange("D11").format={fill:amber,font:{name:font,size:10,bold:true,color:"#7F6000"},wrapText:true,verticalAlignment:"top",rowHeight:70};summary.getRange("A:A").format.columnWidth=28;summary.getRange("B:B").format.columnWidth=22;summary.getRange("D:D").format.columnWidth=70;

const mon=addSheet("Outcome Monitoring","Delayed-Outcome Model Monitoring","Outcome-dependent metrics appear only after the 12-month observation window matures");
const mr=p.v6_delayed_monitoring;mon.getRange("A6:K6").values=[["Month","Applications","Label maturity","Mean PD","Observed bad rate","AUC","KS","Calibration gap","Score PSI","Status","Action"]];mon.getRangeByIndexes(6,0,mr.length,11).values=mr.map(r=>[r.month,r.applications,r.label_maturity_rate,r.mean_pd,r.observed_bad_rate,r.auc_when_mature,r.ks_when_mature,r.calibration_gap_when_mature,r.score_psi,r.status,r.action]);header(mon.getRange("A6:K6"));body(mon.getRangeByIndexes(6,0,mr.length,11));mon.getRange(`C7:I${6+mr.length}`).format.numberFormat=pct;mon.getRange("A:A").format.columnWidth=12;mon.getRange("B:J").format.columnWidth=15;mon.getRange("K:K").format.columnWidth=47;mon.getRange(`J7:J${6+mr.length}`).conditionalFormats.add("containsText",{text:"RED",format:{fill:"#FFC7CE",font:{bold:true,color:"#9C0006"}}});mon.getRange(`J7:J${6+mr.length}`).conditionalFormats.add("containsText",{text:"AMBER",format:{fill:"#FFEB9C",font:{bold:true,color:"#9C6500"}}});mon.freezePanes.freezeRows(6);

const ecl=addSheet("IFRS9 ECL","IFRS 9 PD–LGD–EAD and Macroeconomic Scenarios","Edit scenario weights in blue; weights must total 100%");
const sc=p.v6_macro_scenarios;ecl.getRange("A6:I6").values=[["Scenario","Weight","GDP growth","Unemployment","Policy rate","PD odds multiplier","LGD add-on","Total EAD","Scenario ECL"]];ecl.getRangeByIndexes(6,0,sc.length,9).values=sc.map(r=>[r.scenario,r.weight,r.gdp_growth,r.unemployment,r.policy_rate,r.pd_odds_multiplier,r.lgd_add_on,r.total_ead,r.total_ecl]);header(ecl.getRange("A6:I6"));body(ecl.getRangeByIndexes(6,0,sc.length,9));ecl.getRange("B7:B9").format={fill:"#DDEBF7",font:{name:font,size:10,bold:true,color:"#0000FF"},numberFormat:pct};ecl.getRange("C7:E9").format.numberFormat=pct;ecl.getRange("G7:G9").format.numberFormat=pct;ecl.getRange("H7:I9").format.numberFormat=money;
ecl.getRange("A11:B13").values=[["Control","Result"],["Weight total",null],["Probability-weighted ECL",null]];header(ecl.getRange("A11:B11"));ecl.getRange("B12").formulas=[["=SUM(B7:B9)"]];ecl.getRange("B13").formulas=[["=SUMPRODUCT(B7:B9,I7:I9)"]];ecl.getRange("B12").format.numberFormat=pct;ecl.getRange("B13").format.numberFormat=money;ecl.getRange("B12").conditionalFormats.add("cellIs",{operator:"notEqual",formula:1,format:{fill:"#FFC7CE",font:{bold:true,color:"#9C0006"}}});
const st=p.v6_ifrs9_stage_summary;ecl.getRange("A16:F16").values=[["Stage","Accounts","Mean PD","Mean LGD","Total EAD","Weighted ECL"]];ecl.getRangeByIndexes(16,0,st.length,6).values=st.map(r=>[r.stage,r.accounts,r.mean_pd,r.mean_lgd,r.total_ead,r.weighted_ecl]);header(ecl.getRange("A16:F16"));body(ecl.getRangeByIndexes(16,0,st.length,6));ecl.getRange("C17:D19").format.numberFormat=pct;ecl.getRange("E17:F19").format.numberFormat=money;
ecl.getRange("H16:I21").values=[["Component","Validation"],["LGD status",p.v6_lgd_validation.status],["LGD MAE",p.v6_lgd_validation.mae],["LGD R-squared",p.v6_lgd_validation.r2],["EAD status",p.v6_ead_validation.status],["EAD MAE",p.v6_ead_validation.mae]];header(ecl.getRange("H16:I16"));body(ecl.getRange("H17:I21"));ecl.getRange("I18:I21").format.numberFormat="0.000";ecl.getRange("A:A").format.columnWidth=18;ecl.getRange("B:G").format.columnWidth=17;ecl.getRange("H:I").format.columnWidth=20;

const deploy=addSheet("Deployment Controls","Shadow, Canary and Rollback Controls","Rollout proceeds only when score, decision, latency and error gates pass");
const dg=p.v6_deployment_gates;deploy.getRange("A6:H6").values=[["Phase","Traffic share","Score match","Decision match","p95 latency ms","Error rate","Status","Next action"]];deploy.getRangeByIndexes(6,0,dg.length,8).values=dg.map(r=>[r.phase,r.traffic_share,r.score_match_rate,r.decision_match_rate,r.p95_latency_ms,r.error_rate,r.status,r.next_action]);header(deploy.getRange("A6:H6"));body(deploy.getRangeByIndexes(6,0,dg.length,8));deploy.getRange("B7:D10").format.numberFormat=pct;deploy.getRange("F7:F10").format.numberFormat=pct;deploy.getRange("G7:G10").conditionalFormats.add("containsText",{text:"ROLLBACK",format:{fill:"#FFC7CE",font:{bold:true,color:"#9C0006"}}});
const rb=p.v6_rollback_drill;deploy.getRange("A14:E14").values=[["Step","Control","Evidence","Owner","Status"]];deploy.getRangeByIndexes(14,0,rb.length,5).values=rb.map(r=>[r.step,r.control,r.evidence,r.owner,r.status]);header(deploy.getRange("A14:E14"));body(deploy.getRangeByIndexes(14,0,rb.length,5));deploy.getRange("A:A").format.columnWidth=16;deploy.getRange("B:D").format.columnWidth=33;deploy.getRange("E:G").format.columnWidth=17;deploy.getRange("H:H").format.columnWidth=45;

const inc=addSheet("Incident Register","Model and Deployment Incident Register","Each alert has a severity, accountable owner, remediation action and response SLA");
const ir=p.v6_incidents;inc.getRange("A6:J6").values=[["Incident ID","Signal","Observed","Amber threshold","Red threshold","Severity","Owner","Action","SLA hours","Status"]];inc.getRangeByIndexes(6,0,ir.length,10).values=ir.map(r=>[r.incident_id,r.signal,r.observed,r.amber_threshold,r.red_threshold,r.severity,r.owner,r.action,r.sla_hours,r.status]);header(inc.getRange("A6:J6"));body(inc.getRangeByIndexes(6,0,ir.length,10));inc.getRange("A:A").format.columnWidth=18;inc.getRange("B:B").format.columnWidth=28;inc.getRange("C:E").format.columnWidth=17;inc.getRange("F:G").format.columnWidth=20;inc.getRange("H:H").format.columnWidth=48;inc.getRange("I:J").format.columnWidth=15;inc.getRange("F7:F10").conditionalFormats.add("containsText",{text:"CRITICAL",format:{fill:"#FFC7CE",font:{bold:true,color:"#9C0006"}}});

wb.recalculate();
const checks=[];for(const [sheet,range] of [["V6 Summary","A2:D15"],["Outcome Monitoring","A2:K23"],["IFRS9 ECL","A2:I21"],["Deployment Controls","A2:H20"],["Incident Register","A2:J10"]])checks.push((await wb.inspect({kind:"table",range:`${sheet}!${range}`,include:"values,formulas",tableMaxRows:30,tableMaxCols:12})).ndjson);
ecl.getRange("B7:B9").values=[[.10],[.20],[.70]];wb.recalculate();checks.push((await wb.inspect({kind:"table",range:"IFRS9 ECL!A11:B13",include:"values,formulas",tableMaxRows:5,tableMaxCols:3})).ndjson);ecl.getRange("B7:B9").values=sc.map(r=>[r.weight]);wb.recalculate();
const errors=await wb.inspect({kind:"match",searchTerm:"#REF!|#DIV/0!|#VALUE!|#NAME\\?|#N/A|#NUM!|#NULL!|#SPILL!|#CALC!",options:{useRegex:true,maxResults:300},summary:"final formula error scan"});checks.push(errors.ndjson);await fs.writeFile(`${outputPath}.inspect.ndjson`,checks.join("\n"));
for(const name of ["V6 Summary","Outcome Monitoring","IFRS9 ECL","Deployment Controls","Incident Register"]){const b=await wb.render({sheetName:name,autoCrop:"all",scale:1,format:"png"});await fs.writeFile(`${previewDir}/${name.toLowerCase().replaceAll(" ","_")}.png`,new Uint8Array(await b.arrayBuffer()))}
const out=await SpreadsheetFile.exportXlsx(wb);await out.save(outputPath);console.log(JSON.stringify({outputPath,sheetsAdded:5,errorScan:errors.ndjson}));
