import fs from "node:fs/promises";
import {FileBlob,SpreadsheetFile} from "@oai/artifact-tool";
const root="/workspace/scratch/82fa5d97afa7/retail_credit_pd_model",source=`${root}/outputs/v7/model_validation_pack_v7.xlsx`,dir=`${root}/outputs/v8`,out=`${dir}/model_validation_pack_v8.xlsx`,pre=`${dir}/previews`;
const p=JSON.parse(await fs.readFile(`${root}/reports/validation_payload.json`,"utf8"));await fs.mkdir(pre,{recursive:true});const wb=await SpreadsheetFile.importXlsx(await FileBlob.load(source));
const navy="#123455",gold="#F2B705",blue="#DDEBF7",pale="#EDF4F8",amber="#FFF2CC",font="Arial",pct="0.0%",money='"VND "#,##0;[Red]("VND "#,##0);-';
function add(name,title,note){const s=wb.worksheets.add(name);s.showGridLines=false;s.getRange("A2:J2").merge();s.getRange("A2").values=[[title]];s.getRange("A2:J2").format={font:{name:font,size:16,bold:true,color:navy},rowHeight:27};s.getRange("A3:J3").merge();s.getRange("A3").values=[[note]];s.getRange("A3:J3").format={font:{name:font,size:10,italic:true,color:"#666666"},rowHeight:19};s.getRange("A4:J4").format.borders={bottom:{style:"medium",color:gold}};return s}
function head(r){r.format={fill:navy,font:{name:font,size:10,bold:true,color:"#FFFFFF"},horizontalAlignment:"center",verticalAlignment:"center",wrapText:true,rowHeight:28}}
function body(r){r.format={font:{name:font,size:10,color:"#1F1F1F"},verticalAlignment:"center",wrapText:true,borders:{insideHorizontal:{style:"thin",color:"#D9E2F3"}}}}

const s=add("V8 Summary","V8 TNEX Digital Lending Operating System","Interactive synthetic portfolio; not an official TNEX model or affiliated implementation");
s.getRange("A6:B15").values=[["Metric","Result"],["Build",p.v8_summary.build],["Products",p.v8_summary.live_products],["Product models",p.v8_summary.product_models],["Fraud clusters",p.v8_summary.fraud_clusters],["Recommended credit cut-off",p.v8_summary.recommended_credit_cutoff],["Recommended fraud cut-off",p.v8_summary.recommended_fraud_cutoff],["Recommended approval rate",p.v8_summary.recommended_approval_rate],["Recommended contribution",p.v8_summary.recommended_contribution_vnd],["Recommended RAROC",p.v8_summary.recommended_raroc]];head(s.getRange("A6:B6"));body(s.getRange("A7:B15"));s.getRange("B11:B13").format.numberFormat=pct;s.getRange("B14").format.numberFormat=money;s.getRange("B15").format.numberFormat=pct;
s.getRange("D6:H6").merge();s.getRange("D6").values=[["Operating conclusion"]];head(s.getRange("D6:H6"));s.getRange("D7:H10").merge();s.getRange("D7").values=[["V8 combines live product decisions, separate product calibration evidence, linked-device fraud intelligence, constrained risk–profit optimization and collections next-best-action. Pending payments suppress automated contact until reconciliation."]];s.getRange("D7:H10").format={fill:pale,font:{name:font,size:11,color:navy},wrapText:true,verticalAlignment:"center"};s.getRange("D12:H12").merge();s.getRange("D12").values=[["Production requirements"]];head(s.getRange("D12:H12"));s.getRange("D13:H15").merge();s.getRange("D13").values=[["Use approved data, independently validate each model, complete privacy and consent assessment, calibrate unit economics, integrate the ledger, and complete shadow and canary releases."]];s.getRange("D13:H15").format={fill:amber,font:{name:font,size:10,bold:true,color:"#7F6000"},wrapText:true,verticalAlignment:"center"};s.getRange("A:A").format.columnWidth=30;s.getRange("B:B").format.columnWidth=23;s.getRange("D:H").format.columnWidth=15;

const o=add("Strategy Optimizer","Risk and Profit Strategy Optimizer","Blue cells are editable; formulas retrieve the matching simulated strategy");o.getRange("A6:D6").values=[["Selected credit cut-off",p.v8_summary.recommended_credit_cutoff,"Selected fraud cut-off",p.v8_summary.recommended_fraud_cutoff]];head(o.getRange("A6"));head(o.getRange("C6"));o.getRange("B6").format={fill:blue,font:{name:font,size:10,bold:true,color:"#0000FF"},numberFormat:pct};o.getRange("D6").format={fill:blue,font:{name:font,size:10,bold:true,color:"#0000FF"},numberFormat:pct};
o.getRange("A8:H8").values=[["Approval rate","Approved accounts","Approved exposure","Expected credit loss","Expected fraud loss","Contribution","RAROC","Recommendation"]];head(o.getRange("A8:H8"));o.getRange("A9").formulas=[["=SUMIFS(D14:D28,A14:A28,$B$6,B14:B28,$D$6)"]];o.getRange("B9").formulas=[["=SUMIFS(E14:E28,A14:A28,$B$6,B14:B28,$D$6)"]];o.getRange("C9").formulas=[["=SUMIFS(F14:F28,A14:A28,$B$6,B14:B28,$D$6)"]];o.getRange("D9").formulas=[["=SUMIFS(G14:G28,A14:A28,$B$6,B14:B28,$D$6)"]];o.getRange("E9").formulas=[["=SUMIFS(H14:H28,A14:A28,$B$6,B14:B28,$D$6)"]];o.getRange("F9").formulas=[["=SUMIFS(I14:I28,A14:A28,$B$6,B14:B28,$D$6)"]];o.getRange("G9").formulas=[["=SUMIFS(J14:J28,A14:A28,$B$6,B14:B28,$D$6)"]];o.getRange("H9").formulas=[["=IF(AND(B6=12%,D6=30%),\"RECOMMENDED\",\"ALTERNATIVE\")"]];o.getRange("A9").format.numberFormat=pct;o.getRange("G9").format.numberFormat=pct;o.getRange("C9:F9").format.numberFormat=money;
const opt=p.v8_optimizer;o.getRange("A13:J13").values=[["Credit cut-off","Fraud cut-off","Recommended","Approval rate","Accounts","Exposure","Expected loss","Fraud loss","Contribution","RAROC"]];o.getRangeByIndexes(13,0,opt.length,10).values=opt.map(x=>[x.credit_pd_cutoff,x.fraud_cutoff,x.recommended,x.approval_rate,x.approved_accounts,x.approved_exposure_vnd,x.expected_loss_vnd,x.fraud_loss_vnd,x.contribution_vnd,x.raroc]);head(o.getRange("A13:J13"));body(o.getRange("A14:J28"));o.getRange("A14:B28").format.numberFormat=pct;o.getRange("D14:D28").format.numberFormat=pct;o.getRange("F14:I28").format.numberFormat=money;o.getRange("J14:J28").format.numberFormat=pct;o.getRange("A:J").format.columnWidth=17;o.freezePanes.freezeRows(13);

const l=add("Live Decisions","Live Decision Examples and Product Models","Representative synthetic applications show auditable model and policy outputs");const cases=p.v8_live_cases;l.getRange("A6:J6").values=[["Application","Product","Decision","Primary reason","Base PD","Product PD","Score","Fraud score","Approved limit","Policy version"]];l.getRangeByIndexes(6,0,cases.length,10).values=cases.map(x=>[x.application_id,x.product,x.decision,x.primary_reason,x.base_pd,x.product_pd,x.credit_score,x.fraud_score,x.approved_limit_vnd,x.policy_version]);head(l.getRange("A6:J6"));body(l.getRange("A7:J9"));l.getRange("E7:F9").format.numberFormat=pct;l.getRange("H7:H9").format.numberFormat=pct;l.getRange("I7:I9").format.numberFormat=money;
const pm=p.v8_product_models;l.getRange("A13:H13").values=[["Product","Model ID","Rows","Predicted PD","Observed bad rate","Calibration gap","Policy version","Status"]];l.getRangeByIndexes(13,0,pm.length,8).values=pm.map(x=>[x.product,x.model_id,x.development_rows,x.mean_predicted_pd,x.observed_bad_rate,x.calibration_gap,x.policy_version,x.status]);head(l.getRange("A13:H13"));body(l.getRange("A14:H16"));l.getRange("D14:F16").format.numberFormat=pct;l.getRange("A:A").format.columnWidth=20;l.getRange("B:D").format.columnWidth=24;l.getRange("E:J").format.columnWidth=18;

const c=add("Fraud and Collections","Fraud Network and Collections Next-Best-Action","Linked-device risks and customer-treatment controls remain separate and explainable");const net=p.v8_fraud_network;c.getRange("A6:G6").values=[["Device cluster","Linked applications","Products","Mean fraud score","Requested amount","Risk","Action"]];c.getRangeByIndexes(6,0,net.length,7).values=net.map(x=>[x.device_cluster,x.linked_applications,x.products,x.mean_fraud_score,x.requested_amount_vnd,x.risk_level,x.action]);head(c.getRange("A6:G6"));body(c.getRangeByIndexes(6,0,net.length,7));c.getRange(`D7:D${6+net.length}`).format.numberFormat=pct;c.getRange(`E7:E${6+net.length}`).format.numberFormat=money;
const nba=p.v8_collections_nba;c.getRange("I6:M6").values=[["Next-best-action","Accounts","Mean DPD","Mean PD","Contact allowed"]];c.getRangeByIndexes(6,8,nba.length,5).values=nba.map(x=>[x.nba,x.accounts,x.mean_dpd,x.mean_pd,x.contact_allowed]);head(c.getRange("I6:M6"));body(c.getRangeByIndexes(6,8,nba.length,5));c.getRange(`L7:M${6+nba.length}`).format.numberFormat=pct;c.getRange("A:A").format.columnWidth=17;c.getRange("B:D").format.columnWidth=18;c.getRange("E:E").format.columnWidth=24;c.getRange("F:F").format.columnWidth=14;c.getRange("G:G").format.columnWidth=29;c.getRange("I:I").format.columnWidth=39;c.getRange("J:M").format.columnWidth=17;

wb.recalculate();const checks=[];for(const [sn,r] of [["V8 Summary","A2:H15"],["Strategy Optimizer","A2:J28"],["Live Decisions","A2:J16"],["Fraud and Collections","A2:M26"]])checks.push((await wb.inspect({kind:"table",range:`${sn}!${r}`,include:"values,formulas",tableMaxRows:32,tableMaxCols:14})).ndjson);
o.getRange("B6").values=[[.10]];o.getRange("D6").values=[[.20]];wb.recalculate();checks.push((await wb.inspect({kind:"table",range:"Strategy Optimizer!A6:H9",include:"values,formulas",tableMaxRows:6,tableMaxCols:9})).ndjson);o.getRange("B6").values=[[p.v8_summary.recommended_credit_cutoff]];o.getRange("D6").values=[[p.v8_summary.recommended_fraud_cutoff]];wb.recalculate();
const errors=await wb.inspect({kind:"match",searchTerm:"#REF!|#DIV/0!|#VALUE!|#NAME\\?|#N/A|#NUM!|#NULL!|#SPILL!|#CALC!",options:{useRegex:true,maxResults:300},summary:"final formula error scan"});checks.push(errors.ndjson);await fs.writeFile(`${out}.inspect.ndjson`,checks.join("\n"));for(const name of ["V8 Summary","Strategy Optimizer","Live Decisions","Fraud and Collections"]){const b=await wb.render({sheetName:name,autoCrop:"all",scale:1,format:"png"});await fs.writeFile(`${pre}/${name.toLowerCase().replaceAll(" ","_")}.png`,new Uint8Array(await b.arrayBuffer()))}const blob=await SpreadsheetFile.exportXlsx(wb);await blob.save(out);console.log(JSON.stringify({outputPath:out,errorScan:errors.ndjson,sheetsAdded:4}));
